---
- hosts: guests:extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - git: repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    - shell: /home/isucon/.xbuild/go-install 1.25.7 /home/isucon/.local/go $(uname -s | tr [A-Z] [a-z]) $(dpkg --print-architecture)
      args:
        creates: /home/isucon/.local/go/bin/go
